### PR TITLE
backported sneak pickup feature to 1.7.10

### PR DESCRIPTION
**Pull request by facetorched**
This feature from future versions is great and I would love to have this merged and built into a release! I think players on 1.7.10 would appreciate it.

I tried to keep the code as similar to the future implementation while respecting the rest of the code in this version as to (hopefully) not introduce any bugs. Of course some re-factoring could be done to make the overall code cleaner, but I decided against modifying existing classes as much as possible.

### CODE REVIEW

**Comment by henkelmax** [comment]
Sorry, but this version is unsupported for a couple of years now.
I can't even get the workspace running anymore.

**Comment by facetorched** [comment]
@henkelmax ah understandable. I am able to get it running with a new buildscript. I could create a PR for that but it sounds like you are unwilling to accept contributions for this version.

That said, given there is no license for this project, how flexible would you be for me to pick up support for this old version of the game? e.g. distributing releases etc.

**Comment by henkelmax** [comment]
This version is over 8 years old. I don't have the time to put any work into this. I'm sorry.

**Comment by facetorched** [comment]
No problem I just want to be respectful of your work. I take it that you have no issues with me continuing development? I will of course credit you and the original developers

**Comment by henkelmax** [comment]
As long as you don't release the mod on any mod distribution pages (Like CurseForge or modrinth), thats fine for me.

**Comment by facetorched** [comment]
Hm. That's too bad since I'd like to be able to have these fixes on a public modpack and server. Well I guess this is what I get for not asking first!
does github count as a mod distribution page? I could post a release on my fork.

**Pull request closed without merging**
