### PR TITLE
Slightly improved all translation files

### PR DESCRIPTION
**Pull request by Greg-21**
In this pull request I did the following:
* added missing newline characters at the ends of translation files, as I've seen that you're using them in your Java code as well
* changed "Ghost Player" to "Ghost of Player" because probably that's what you intended to have here. Alternatively, "Player Ghost" can be used here as well, I think
* slightly changed the wording of two sentences to make them be more accurate and sound a bit better
* reduced indentations in the Swedish translation from 4 to 2 characters for consistency with all the other translations
* removed line `gui.obituary.page` from all translation files that had only one `%s` operator instead of two. This is the most controversial change, and I'm not entirely sure that it's a positive thing, so please let me know what you think about it.

If you don't like some of the changes, also please let me know, as I can always modify them and this PR.

### CODE REVIEW

**Comment by henkelmax** [comment]
Thank you!
Why did you remove the translations for `gui.obituary.page`?
Every translation except german and english is a little older, so they were based off of another version that had only one number, but they still work. They just show `Page 1` instead of `Page 1 of 2` for example.

**Comment by Greg-21** [comment]
Are there any problems when your Java code tries to put two things, but there is only one `%s`? If not, then my fears are groundless, and I should re-add the line.

**Comment by Greg-21** [comment]
Are there any problems when your Java code tries to put two things, but there is only one `%s`? If not, then my fears are groundless, and I should re-add the line (maybe with some help from your Corpse mod?).

**Comment by henkelmax** [comment]
I tried it and it works with two parameters, but only one `%s`. It just takes the first parameter, so it works fine.

**Comment by Greg-21** [comment]
Okay, thanks for letting me know.

**Comment by henkelmax** [comment]
Thank you!

**Pull request merged**
